#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication decomposePar -copyZero
runParallel snappyHexMesh -overwrite
runParallel transformPoints "scale=(0.02 0.02 0.02)"
runParallel renumberMesh -overwrite
runParallel $(getApplication)
runApplication reconstructPar
